language: python

python:
    - '3.3'

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - cd blog_frontend
  - npm install --quiet -g grunt-cli karma bower
  - npm install
  - bower install

script: grunt

deploy:
  provider: pypi
  user:
    secure: NBTv0H+PBRpa5cZ3OEnSQzyYoMohGycKxKbkgPceZkUk5uwFeES67QVrCl5Qib/j+lil9r+7RXNINeXvAm7vo0aZeNnPAk6kHQmiUsKVuLFECWQrwgUq3DszLYYSEy5Hx01Llu6DxoEYdhw2nIXEoku4k+smKKY3AtCCbBhFIIzSp45euogfRw/Yl+iT7RJak/9lgAfl398a1sOW36CWXaylBjqo45kXmzggEFweAjaMaDPz6Hcy7oj1oIPiFIS1dXRPo8l9YCO9ZUqxD8VAZH3Y/v61xqi1TdLtta6lKYEyy1GjaX+XlDNeAPVlUPpVpihU75KoEfEo5P7IbpuUT1UjiT4CKHnk0gOV+GwbvFs5HNk4yJoTsWnMOZyvSRvwFUvYGydTXfFfBYFO95FitDfT3bwWohzAEG92AlH9cuQA9WreGy+ziej2JMdsSzhxVEaYK1xbsu8RtxcQuMw/OOR9EnkeTyuhrOV1fc7k/4ehWX3Tn9AxI5SvRJoztkeTNmohxRjNDOODA+FKEvbK5B/bYbxy15KS3gFpMO5XSHXdXp9OiDY4oUaG79KDcD+dTsxL0ReQFU/8HV2SgavU35Wl8D3u8NmmIkR5wocHlS9exzC4axKy9j/frjP4XRH1RbvYxFCNKlwEETnmpNAYgYL0wz1H9yzxMkCVKuaGhfM=
  password:
    secure: Sw0b5OwlzpEtZUSQ2wR1/pwCx1b21PjNKjX8U/F3rL7RyNET3KcOMNeATWnfL2Uoj5t2nmpXRK/cewz05514nc+Kq92jScOL7C6ka5G5dczpCYHpRk/cXurNn/WQ174rsUgZiiNkWJacyC9DURrmpmD9X9WOrpzI5ZiBe7rbWNW4bwKJyHeYjnw1TWxv6Sq+65eDERTnf/nqtYP2m1nxtKW4YGfuukSyDVYrWA4qn3AUWbA51XS5KtbvwuJMnB58oEbgrjNZYLze9rQ630sJ4LEhqOi9R7O4U+5ayu29nAc24K/TkOx3A+nd8xybyh4h3Ird1AZgMkfM8NbaRR2IbaFZuKsPoox1WE6BYOiWXb8QGWInXCZCqbfpqIQScFdaJJ+ENfMnoHsk2ptOM1WSnnAYNTAdLRzRCaTe1AruhoNiC4hsDx2JttjVwm+/44FjvzmjqR5eKYrfz88VITFWnmLYnIz4Rj/r0e78Og24TIYZsvFTxVefhN6DyOMQ+J8YVoWEO01CnzGkFihWHQNxj3HZSWFl6GT6uf8dkAp8qK0T/lyDJVqanHoRaVUdfPjUUcdONJZRc8gLHP3SLHGdx72fLvK5GZG3ClS0mp9YzLV+lWLf41xvLq7qSISdA6YsReyp2pACzirlj32BB0lTOVBY4FmlSFpRE1WYY2bAocg=
  on:
    repo: enkidulan/blog_frontend
  server:
    secure: hWn/GQ7nk1Bewklh7+RXFFyaofzwL52spjowKt/Ym4YIaPJqGEvRF4Fw4ve76/ouuYg9uLOTr7TKYxRG0iAZ+ILhfoBuW3nbayRn2Jw98+509gmcwwYXFfjuC1qxQP74iQi1LgSFA2VM3U9N9junU8Ya44D8Hu1f6t+E2cYUT64vBDBZwT2e0cQPIecN+GARCRlTKfm7O28tSmr9bXdOUecnXYeHgV9XHRQx0AxEwVZ14yOo/M0GR7d87WQ+Ku89QFv74E7w8Kj0P4q9EYFmy+Wg+KSKuICSuIqozjvY2+pPu463KwlLtX4KCbreSsXVqvHb/Kv+p37NVnWhVN7UHGovBkVzmGnyjmVXJyyYkbablevf+scizLTlMQNjvrfN2+qOeJEK4f1uEtIe15eeh5do56ky2q6CaTN0BNfWBzkMJJKNgDAqBTP0/SSpEg/gYyFiuGcbLdFUzkYeshrgVNXsY7YvgZhiC2nNEq5TlwLiVTDOKbwhULzJJnwulWigiMhx0dvjcmS0E8NaPz0u/F1Kwh7rUBqfmf3g16RUztPi90R0NFC2MaHPrHT75iZTzjqSKODKfNIZiU3LuVZtNHIdaKXTXg/v1jHEXcEYns63pgLtG4TFklHqCAjgHeC3hdPuhXBYnaA0pinjV/5kwM8f/dQBTB5UwekpkBetqcQ=
