language: python
env:
- TAGNAME=`date +"%Y%m%d-%H%M"`
python:
- "3.4"
before_script:
- sudo apt-get update --fix-missing
- sudo apt-get install -qq nodejs npm
- cd blog_frontend
- git rm bin -rf
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install --quiet -g grunt-cli karma bower
- npm install
- bower install
after_success:
- ls
- git status
- git add bin
- cd ..
- ls
- sed -ri s/version=\'[0-9\-]+.\'/version=\'$TAGNAME\'/g setup.py
- cat setup.py
- git add setup.py
- git commit -m "preparing new version $TAGNAME" --author 'BuildBot <enkidulan@gmail.com>'
- git fetch --tags
- git tag $TAGNAME
- git push master origin
- git push --tags
script: grunt
